name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version: '1.21'

    - name: Get
      run: go get -v

    - name: lint
      uses: golangci/golangci-lint-action@v3.4.0
      with:
        args: ./...
        version: v1.55.2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
